BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `users` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`login`	TEXT NOT NULL UNIQUE,
	`password`	TEXT,
	`email`	TEXT,
	`money`	INTEGER NOT NULL DEFAULT 0,
	`record`	INTEGER NOT NULL DEFAULT 0
);
INSERT INTO `users` VALUES (1,'Гость','','',0,0);
CREATE TABLE IF NOT EXISTS `resume` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`mode`	INTEGER NOT NULL DEFAULT 1,
	`score`	INTEGER NOT NULL DEFAULT 0,
	`all_rewards`	INTEGER NOT NULL DEFAULT 0,
	`score_1`	INTEGER NOT NULL DEFAULT 0,
	`all_rewards_1`	INTEGER NOT NULL DEFAULT 0,
	`score_2`	INTEGER NOT NULL DEFAULT 0,
	`all_rewards_2`	INTEGER NOT NULL DEFAULT 0,
	`score_3`	INTEGER NOT NULL DEFAULT 0,
	`all_rewards_3`	INTEGER NOT NULL DEFAULT 0,
	`score_4`	INTEGER NOT NULL DEFAULT 0,
	`all_rewards_4`	INTEGER NOT NULL DEFAULT 0,
	`id_user`	INTEGER,
	FOREIGN KEY(`id_user`) REFERENCES `users`(`_id`) ON DELETE CASCADE
);
INSERT INTO `resume` VALUES (1,1,0,0,0,0,0,0,0,0,0,0,1);
CREATE TABLE IF NOT EXISTS `remember` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`login`	TEXT,
	`password`	TEXT
);
INSERT INTO `remember` VALUES (1,NULL,NULL);
CREATE TABLE IF NOT EXISTS `achievements` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`status`	TEXT NOT NULL DEFAULT '00000000000000000000000000',
	`all_levels`	INTEGER NOT NULL DEFAULT 0,
	`all_money`	INTEGER NOT NULL DEFAULT 0,
	`all_eating`	INTEGER NOT NULL DEFAULT 0,
	`all_wins`	INTEGER NOT NULL DEFAULT 0,
	`id_user`	INTEGER,
	FOREIGN KEY(`id_user`) REFERENCES `users`(`_id`) ON DELETE CASCADE
);
INSERT INTO `achievements` VALUES (1,'00000000000000000000000000',0,0,0,0,1);
COMMIT;
